### ISSUE TITLE
Deployment  🤔💡 

### ISSUE THREAD

**Issue by igbanam** [ahndawn/Warbler-Twitter-clone#1]
>Disclaimer: This is a stretch goal which you're not required to hit; since it just popped into my mind as an idea now.

Since we spoke about deployments last time, and we learned about some free cloud options: Fly.io and Render.com, maybe you could try putting this up on one of those services?

Only attempt this when you're done with the requirements listed in the assessment, and when you're comfortable with how localhost looks and feels

**Comment by MissMahnster** [comment]
I will definitely give it a shot once it's all done!

**Comment by MissMahnster** [comment]
got it to work on render! https://warblertwitterclone.onrender.com/
